version: 2

before:
  hooks:
    - go install github.com/a-h/templ/cmd/templ@latest
    - templ generate

builds:
  - id: datetree
    main: .
    binary: datetree
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{ .Tag }}

archives:
  - id: datetree
    name_template: "datetree_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    files:
      - LICENSE*
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
